#服务器端口
server:
  port: 9998

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-0kq96jne.sql.tencentcdb.com:26311/cloud_share?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: liushupeng
    password: Liushupeng+1635335
